// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYqZqftyTiIG9BE4Y22938I4CI49rvzw',
    appId: '1:991421887042:web:1b69210aa90e68575373db',
    messagingSenderId: '991421887042',
    projectId: 'instagram-login-signup-db963',
    authDomain: 'instagram-login-signup-db963.firebaseapp.com',
    storageBucket: 'instagram-login-signup-db963.appspot.com',
    measurementId: 'G-QHPRJN0EDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2V3j3Ay-X8FwdO97-9PGZqHbAhwgSKrs',
    appId: '1:991421887042:android:63056de7c54660e25373db',
    messagingSenderId: '991421887042',
    projectId: 'instagram-login-signup-db963',
    storageBucket: 'instagram-login-signup-db963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbbevj2XqDMTv8i6miRfyjd84sBpYwZI',
    appId: '1:991421887042:ios:9f2e8b288ea802b65373db',
    messagingSenderId: '991421887042',
    projectId: 'instagram-login-signup-db963',
    storageBucket: 'instagram-login-signup-db963.appspot.com',
    iosBundleId: 'com.example.firebaseLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbbevj2XqDMTv8i6miRfyjd84sBpYwZI',
    appId: '1:991421887042:ios:3964486c8371bc795373db',
    messagingSenderId: '991421887042',
    projectId: 'instagram-login-signup-db963',
    storageBucket: 'instagram-login-signup-db963.appspot.com',
    iosBundleId: 'com.example.firebaseLoginSignup.RunnerTests',
  );
}
